// These connecting chapters use only events, documents and motives already in each mystery.
const chapters = {
  manor: [
    {
      title: 'Round 2 - Debts in the Dark',
      narration: 'The broken glass remains beneath the table while the living begin to count what the dead man owed them. Money, employment, a reputation, a place in this house: Ambrose could grant or destroy them all. The brandy was poured before the candles failed. The darkness came later.\n\nA cut stalk of monkshood and a trail of soil turn the conservatory into something more than a garden. An old tonic bottle, fetched at Ambrose\'s request, bears the initials S.A. He wanted it kept for the constable after tonight. He expected an answer from this gathering. Instead, he became its second unanswered death.\n\nListen to the accusations. A motive explains why someone feared Ambrose. It does not yet explain which hand reached his glass.',
      publicText: 'Debts, threatened reputations and the tonic bottle deepen suspicion. Separate access to the drinks from movements during the blackout.',
    },
    {
      title: 'Round 4 - What the Darkness Hid',
      narration: 'The accusations have made every secret sound like murder. Now put the secrets beside the evidence. Brandy from the same decanter did not kill everyone who drank it. A hidden wire explains the knocking, and Ambrose\'s script explains why the medium was hired. Neither explanation makes the poison disappear.\n\nThe question is changing. It is no longer simply who wanted Ambrose dead, but who could turn a planned darkness into an opportunity. The stolen silver, withheld warnings and concealed letters explain why witnesses hesitated. Their shame has obscured the account of the night; it has not made every witness a murderer.\n\nRead the new evidence carefully. Where it corrects an earlier accusation, keep both entries. The correction matters as much as the suspicion.',
      publicText: 'The clean decanter weakens the accusation against the pourer. The script explains the staged seance. Revisit the glass, the tonic and the witnesses without mistaking every secret for murder.',
    },
  ],
  witch: [
    {
      title: 'Round 2 - The Price of a Name',
      narration: 'Ward\'s missing packet has left a room full of people who would rather not have their names written down. An angry letter, a withdrawn testimony, a concealed traveler and disputed fees all seem sinister under candlelight. Yet each had a history before Ward went into the records room.\n\nThe black ribbon supplies fear, not a reliable account of who passed through that door. The grain argument and the village debts supply motives, not a timeline. Ward had begun to question the hearings and the deeds taken from accused families. Some guests feared that investigation; others needed it to succeed.\n\nHear every public clue. Ask which secret would be exposed by the packet, and which person could actually have taken it. Do not let the loudest accusation decide what the evidence means.',
      publicText: 'Letters, fees and false testimony give many villagers reasons for secrecy. The missing packet and entry to the records room still need an explanation.',
    },
    {
      title: 'Round 4 - The Fear Behind the Lies',
      narration: 'The confession from a watched prisoner cannot explain a human death in this meetinghouse. The ribbon is ordinary mourning cloth. Put those frightening objects beside the less dramatic papers: receipts, a retraction, a draft rescued before the meeting.\n\nThe midwife concealed a sister to protect her. The witness came to withdraw false testimony. Other guests hid travelers, threats or debts. Those acts have consequences, but they do not become proof of murder merely because the village is afraid.\n\nThe rescued draft repeats the confession\'s phrase. The scorched deed preserves a payment column. A chain clasp needed repair after the meeting began. Each is a small earthly fact. Listen as this round\'s clues correct earlier suspicions, then ask whether the same explanation can account for the papers and the missing packet.',
      publicText: 'Protective lies and ordinary ribbon weaken the supernatural story. Compare the draft, payments and broken chain with the corridor testimony.',
    },
  ],
  farm: [
    {
      title: 'Round 2 - A Farm Worth Fighting For',
      narration: 'The stranger\'s cap sits beside the torn map. Beyond the window, snow removes the road a little more with every minute. Inside, nobody can erase what Otto intended to discuss: the sale of this farm and a lie inside the offer.\n\nAn inheritance, unpaid wages, stolen food and missing spare parts make the household look guilty in different ways. The survey coat is missing a brass button. The workshop side door was not forced. Those details deserve questions, but an object out of place is not yet a complete account of a death.\n\nThe north spring makes the offer valuable. Whoever changed its boundary changed what the farm would be worth to the people gathered here. Let the accusations establish those interests before deciding whether the footsteps belonged to an outsider at all.',
      publicText: 'The sale, spring and household secrets provide competing motives. The unforced door and missing button must fit a timeline, not just a rumor.',
    },
    {
      title: 'Round 4 - The Stranger Falls Apart',
      narration: 'The attic room is real. So are the concealed stair and the sketches. But a real hiding place does not make every story told about it true. The cap was already in the spare-clothes basket. The footprints by the woods are older than tonight\'s snow.\n\nSome missing food fed a struggling neighbor. The original plan was hidden to preserve it. The mechanic repaired the stair at the surveyor\'s request. These explanations do not excuse every theft or lie; they separate the household\'s secrets from the false intruder story.\n\nLay the original boundary beside the amended one. Listen to the account from the kitchen window. The next question is not whether somebody could hide above the beams, but who knew that route, who profited from moving the spring, and who left the workshop after Otto entered.',
      publicText: 'The cap and old tracks no longer establish a new visitor. The original plan and window timeline clarify earlier suspicions; the altered spring boundary remains unexplained.',
    },
  ],
  victorian: [
    {
      title: 'Round 2 - What the Will Really Cost',
      narration: 'In the drawing room, a missing will quickly becomes whatever each frightened guest imagines it must have said. The nephew speaks of ruin. The daughter remembers an argument. Staff wonder whether an audit would take their positions. Cecily had made respectability expensive for everyone.\n\nBut the secretary\'s tray contains a duplicate. The family still inherits. The adviser loses the trusteeship and must account for unexplained withdrawals. A letter Cecily wrote that afternoon demands repayment before she goes to the bank.\n\nHear the public evidence before repeating the inheritance rumor. A private grievance can explain a raised voice. The terms of a surviving document can show whose future was actually threatened. The missing account page must belong to the same story as the missing will.',
      publicText: 'The duplicate will preserves family inheritances but removes the solicitor as trustee. Distinguish the household quarrels from the threatened repayment.',
    },
    {
      title: 'Round 4 - An Alibi Made of Sound',
      narration: 'The bell seemed a precise moment when everyone first heard it. Now the housekeeper explains that its sound continues after the cord is pulled. A person heard in the corridor while it rings may already have left the study.\n\nOther corrections are just as important. The daughter was not disinherited. The nephew never read the will he condemned. The housekeeper\'s small household theft was not the large trust withdrawal, and the physician\'s complaint remained on the desk while the financial papers vanished.\n\nNone of those facts makes every guest honest. They make the accusations more exact. Read the clues, preserving the difference between a hidden embarrassment and an explanation of the crime. Before the final accounting, compare the appointment, the receipt for the new will and the order of the corridor footsteps.',
      publicText: 'The ringing bell is not a secure alibi. The duplicate will and scale of the missing funds correct earlier accusations. Compare access, timing and targeted documents.',
    },
  ],
};

export function expandChapters(story, kind) {
  const original = story.rounds;
  const additions = chapters[kind];
  if (original.length !== 3 || !additions) throw new Error('Five-round adaptation requires a known three-chapter mystery.');
  const note = 'Read the narration, then let every player read their public clue. Discuss how the evidence changes earlier suspicions; vote before continuing.';
  const added = additions.map((round, i) => ({ ...round, title: i === 0 ? round.title.replace('Round 2', 'Round 3') : round.title, hostNotes: note }));
  story.rounds = [
    { ...original[0], hostNotes: note },
    { ...original[1], hostNotes: note },
    added[0],
    added[1],
    { ...original[2], title: original[2].title.replace(/Round 3/, 'Round 5'), hostNotes: 'Final evidence discussion and round vote. Compare motive, method and opportunity before the reveal.' },
  ];
  for (const c of story.characters) {
    const [first, middle, last] = c.rounds;
    c.rounds = [
      { clues: first.clues.slice(0, 1) },
      { clues: first.clues.slice(1) },
      { clues: middle.clues.slice(0, 1) },
      { clues: middle.clues.slice(1) },
      { clues: [...last.clues] },
    ];
  }
}

export const KILLER_FOURTH_CLUE = {
  manor: '{ashgrove} dismissed the death as a weak heart while recognizing the poison symptoms. The clean decanter narrows the method to Ambrose\'s glass. The physician\'s earlier tonic and the question in Ambrose\'s script make that dismissal harder to accept, even before the final witness accounts are compared.',
  witch: '{clerk} dictated the paid testimony and had a reason to remove its retraction. The matching phrase in the rescued draft ties a village court form to the supposed confession. Those connections remain when protective lies and ordinary ribbon weaken the accusations against other villagers.',
  farm: '{surveyor} knew the stair worked because the mechanic repaired it at his request. The cup and blanket link the attic to the measuring room and an earlier visit. That knowledge contradicts the inaccessible-room claim even after the cap and old tracks weaken the outsider theory.',
  victorian: '{solicitor} collected the new will and was seen leaving before the bell stopped. A bell that keeps ringing does not prove he heard it from elsewhere. The repayment letter and appointment still require an explanation after the inheritance rumor falls apart.',
};

// Round 3 develops an established lead; round 5 weighs it after round 4's corrections.
export const CONNECTING_EVIDENCE = {
  manor: {
    ashgrove: ['{ashgrove} signed Eleanor\'s death certificate as fever, yet her tonic made her lips numb and killed plants when she poured it away. The initials on the bottle now connect a medical judgment to a medicine that needs explaining.', '{ashgrove} had reason to fear the question Ambrose paid to ask: who gave Eleanor the tonic? The glass rim, ring and soil support an opportunity during the blackout, while the old bottle supplies the link Ambrose was investigating. A weak-heart explanation accounts for none of them.'],
    crane: ['{crane} returned to the seance room to pocket a candlestick. That theft puts the butler in the doorway during the darkness, precisely when movements around the glass matter most.', '{crane} was in the doorway, not a claimed innocent elsewhere. The candlestick explains that presence; the description of a serpent-and-staff ring should be judged against the poison on the individual glass. Theft explains concealment without explaining both deaths.'],
    constance: ['{constance} wished Ambrose would join Eleanor during their dinner argument. Beside the gambling debt and the poured drinks, those words make resentment difficult to dismiss.', '{constance} remains the heir, but the drink she shared was harmless. The earlier accusation confused control of the decanter with access to a single rim during darkness. Her report of Eleanor\'s numb lips instead connects tonight to the old tonic.'],
    vesper: ['{vesper} was paid triple to follow Ambrose\'s script and controlled the bellows. The fee and the threatened exposure make the staged darkness look less like an innocent entertainment.', '{vesper} concealed a fraud. Ambrose knowingly hired it to ask a question about the tonic, and died before that line was spoken. That sequence explains the performance without explaining who used its darkness to poison a glass.'],
    grey: ['{grey} heard Eleanor say that her death would come from medicine, not fever. The warning stayed private even when Ambrose demanded justice. Was the priest protecting a confession or protecting a person?', '{grey} failed to pass on a warning, but the warning predates tonight\'s murder. Its medical content supports investigation of the tonic; a threat to report the priest\'s drinking does not explain the poisoned rim or identifying ring.'],
    marsh: ['{marsh} was told to open the codicil if Ambrose did not survive the night. With an audit approaching, delaying that document makes the solicitor\'s handling of the estate look deliberate.', '{marsh} had financial wrongdoing to hide, yet the codicil preserved Ambrose\'s suspicion about Eleanor\'s death certificate. That document would not protect the murderer it describes. Account theft and the poison method require different evidence.'],
    pell: ['{pell} recognized the symptoms immediately and knew that a man carrying a doctor\'s bag had asked about a lethal dose. Knowledge of a poison makes the garden accusation more serious, but a question is not an admission by its answerer.', '{pell} supplied knowledge of the plant and recognized its smell on Eleanor\'s bottles. Garden access establishes a source, not the hand at the glass. The same poison in an old prescribed tonic is the connection the eviction dispute cannot explain.'],
    finch: ['{finch} had come to expose a medium while hiding a dismissal for invented reporting. The developing photograph could be a genuine record or another story sold too confidently; its contents must be checked.', '{finch}\'s image agrees with the doorway account of a ring near Ambrose\'s glass. That independent agreement gives the photograph value despite the reporter\'s false credentials. Being dishonest about a job does not explain the medicine bottle.'],
    wren: ['{wren} kept Eleanor\'s room unchanged and knew that the tonic killed its plants. The devotion that prompted dismissal also gave the maid access to signs of poisoning long before tonight.', '{wren} preserved the diary warning that someone watched Eleanor drink. The room that made the maid look obsessed retained a record the household needed. The dismissal motive does not identify the hand at Ambrose\'s glass.'],
    ivy: ['{ivy} swore Ambrose would regret ending the affair, then returned to his coat after his death. Removing the letters concealed a relationship and disturbed the place where his warning was kept.', '{ivy} concealed love letters, but Ambrose\'s accompanying note asked observers to watch S.A.\'s hands. The same pocket that created suspicion also preserved the victim\'s planned trap. The affair does not explain the earlier tonic poisoning.'],
    vane: ['{vane} knew from a field surgeon that wolfsbane could kill and smelled crushed plants across the table. Knowledge, debt and proximity make the captain worth questioning, even though the revolver is not the apparent method.', '{vane} describes the physician already at Ambrose\'s side when the candles returned. Compare that timing with the reaching hand. The captain\'s gun and debt cannot substitute for evidence of the poison on the rim.'],
    blackwood: ['{blackwood} carried a stolen book describing a poison that resembles heart failure. The occult explanation gave a thief a way to direct attention away from ordinary hands and objects.', '{blackwood} saw gloves removed before the seance and replaced after the lights returned. That observation can support the ring account. The stolen grimoire explains secrecy and poison knowledge, not the prescription of Eleanor\'s tonic.'],
  },
  witch: {
    clerk: ['{clerk} dictated the witness\'s false testimony and arranged payment. The packet held the signed retraction, so taking it could protect more than an ordinary records mistake.', '{clerk} links the bought testimony to the diverted deeds. Ward\'s notebook, the flawed seal, the chain fragment and the corridor account independently support that link. A supernatural warning explains neither a private account nor removed papers.'],
    midwife: ['{midwife} needed Ward to clear a sister\'s name after writing an angry letter. The demand for justice could be mistaken for revenge, particularly while the sister\'s whereabouts stayed concealed.', '{midwife}\'s concealment protected the person endangered by the hearings. Ward\'s change of view offered help, not only a grievance. Anger remains real, but the paid forgery and records-room evidence do not arise from the midwife\'s letter.'],
    minister: ['{minister} rescued a draft before the meeting while still concealing a warning about copied testimonies. That selective silence raises a question: why save a paper but withhold the warning that made it matter?', '{minister} discovered the body and preserved a draft written before the forged confession arrived. Its matching phrase and damaged seal make a checkable account, not an alibi invented from superstition. The minister\'s earlier failure was repeating false certainty.'],
    witness: ['{witness} accepted payment for false testimony and could lose protection if the retraction disappeared. A frightened witness had reason to hesitate over the corridor account.', '{witness}\'s retraction threatened the person who dictated the original testimony. The reported pressure to stay silent fits the stolen packet, while the notebook and physical clues support the account independently of a frightened witness\'s reputation.'],
    miller: ['{miller} kept dishonest grain accounts while the private payment column named the mill. The argument and double fee now need to be separated rather than treated as one undifferentiated debt.', '{miller}\'s grain dishonesty is separate from an unlawful records charge paid by the mill. The double receipt helps expose the fee scheme. It does not place the miller in the room between Ward\'s entry and the minister\'s discovery.'],
    seamstress: ['{seamstress} delivered a coat where land receipts lay on the clerk\'s table. Together with ribbon sales and the hidden cloak, those visits made the seamstress a keeper of other people\'s secrets.', '{seamstress}\'s repair request dates the broken clasp after the meeting began. Ribbon sold to several houses cannot identify a murderer by itself. The request instead tests the timing of the chain evidence without inventing a witch.'],
    innkeeper: ['{innkeeper} heard a boast that a coming land sale would settle the clerk\'s debts. Keeping a hidden guest and unpaid money quiet meant a useful motive stayed inside the common room.', '{innkeeper} can compare the account on the burnt deed with a bill already paid at the inn. That financial link is more specific than the innkeeper\'s own debt. Ward\'s help for the sheltered guest also revises the supposed motive for revenge.'],
    schoolmaster: ['{schoolmaster} recognized the confession\'s resemblance to village court forms. Helping with a retraction gave access to testimony, but that access does not explain why a supposed distant confession used local wording.', '{schoolmaster} preserved Ward\'s request to ask Pike about payments. The threatened school explains why the teacher feared speaking; the written annotation supports a financial investigation, not an occult accusation.'],
  },
  farm: {
    surveyor: ['{surveyor}\'s signature appears on the amended plan that moves the spring. The attic sketches are no longer simply evidence of sleeping in a hidden room: they connect that room to the contested sale.', '{surveyor} knew the repaired stair, changed the valuable boundary and received a separate payment. Otto\'s challenge and the coat button place the financial dispute beside the workshop encounter. A stranger\'s cap cannot account for those connected facts.'],
    heir: ['{heir} wanted a sale and had another buyer in mind, yet the plan she hid differs from the amended one. The question is which boundary would serve her inheritance and which would strip it of the spring.', '{heir} benefits from preserving the true boundary. Hiding the original looked like interference in round 2, but its survival exposes the sale\'s lie. The confrontation note connects Otto\'s decision to the paid survey, not to a new scheme by the heir.'],
    housekeeper: ['{housekeeper} found a chipped cup in the attic matching one from the measuring room. Having blamed missing food on a visitor makes that report hard to assess until her own theft is separated from the hidden room.', '{housekeeper} identifies a survey coat leaving the workshop and no outsider crossing the watched courtyard. Her food theft explains a rumor, not that coat. Compare the sighting with the missing button and the mechanic\'s arrival.'],
    mechanic: ['{mechanic} knew the side door was unforced and the hidden stair worked. Repairing that stair without permission could look like preparing a route until the identity of the person who requested it is considered.', '{mechanic} matches the recovered button to the survey coat and remembers an intact map carried into the workshop. The parts theft explains fear of dismissal, while these observations test the route and confrontation described by other evidence.'],
    neighbor: ['{neighbor} knew the spring was worth more than the disputed pasture. A moved fence post gives a small example of dishonest boundaries, but it is not automatically the same alteration as the sale map.', '{neighbor} had a fence dispute, not the paid amendment diverting the north spring. The old tracks weaken a fresh-outsider theory; familiarity observed near the attic window corroborates building access without proving the neighbor killed Otto.'],
    teacher: ['{teacher} can now explain that the contract assigns spring access using the amended map. Missing that clause made earlier advice damaging even if it was careless rather than bought.', '{teacher}\'s mistake helped the offer appear ordinary. The separate survey fee in the buyer\'s correspondence supplies a different, deliberate incentive. Compare the clause with the original plan before confusing a bad summary with a paid boundary change.'],
    postmaster: ['{postmaster} read the warning to compare maps, then hid the delay. Otto\'s investigation therefore concerned a real contract problem, not merely fear of footsteps above the ceiling.', '{postmaster} handled a parcel of map paper and an invoice addressed to the surveyor. Opening mail was misconduct, but those contents corroborate authorship rather than implicating a new weapon or visitor.'],
    buyeragent: ['{buyeragent} represented the buyer benefiting from spring access. Pressure for a sale links commercial ambition to the false map, but the person drawing the amendment still needs to be identified.', '{buyeragent}\'s employer letter and the separate fee distinguish benefiting from a sale from authoring its fraudulent boundary. The letter names the surveyor; compare that with Otto\'s ledger and the workshop evidence.'],
    musician: ['{musician} heard ordinary movement above the measuring room. An unfamiliar guest using a borrowed surname had made those sounds seem like an outsider\'s story, even though the room and stairs belonged to the farm.', '{musician} escaped a creditor by changing names. The cap predated supper and was taken from the basket by the surveyor. Those corrections remove the supposed physical link to a stranger without declaring the musician\'s debt honest.'],
  },
  victorian: {
    solicitor: ['{solicitor} denies the study meeting, yet the appointment names him and the secretary recorded his collection of the will. The bell continues ringing after it is pulled, so hearing it elsewhere cannot undo those records.', '{solicitor}\'s private practice received the missing funds. Cecily demanded repayment and arranged the meeting he denied. The receipt, appointment, carbon page and exit sighting support one sequence; a missing original cannot erase it.'],
    daughter: ['{daughter} still inherits under the duplicate will. Her hidden letter demands that Pell return money, making the argument about control different from the adviser\'s fear of repayment.', '{daughter} preserved the appointment naming the adviser. The angry argument made her plausible early on, but the will corrects disinheritance and the letter redirects the financial motive. Independence is not the same interest as keeping stolen trust funds.'],
    housekeeper: ['{housekeeper} says the bell sounds after the pull. Her corridor sighting may therefore challenge an alibi rather than establish the time of a later attack, despite her reluctance to invite an account investigation.', '{housekeeper} saw a folded legal document carried out of the study and no intervening entry. Her small theft remains a separate offense. The independent appointment and receipt let the room check her delayed account rather than simply trust or dismiss it.'],
    secretary: ['{secretary} retained a duplicate will that undermines the inheritance rumor. Keeping papers while preparing to leave might look like theft, until Cecily\'s instructions about copies are taken into account.', '{secretary} kept copies on Cecily\'s orders, preserving the transfers and the instruction to confront Pell. What looked like secret hoarding protects the evidence against destruction. The decision to leave does not explain payments to another person\'s practice.'],
    nephew: ['{nephew} still receives enough to address his debts under the surviving will. The adviser encouraged his complaints before supper, giving a false rumor a useful public voice.', '{nephew}\'s debts and false promises remain, but his claim of disinheritance was wrong. The duplicate corrects the early motive, while the encouragement to complain fits attention being drawn away from the trustee\'s accounts.'],
    companion: ['{companion} heard Cecily describe the accounts as someone else\'s purse. The concealed pension and planned departure make that knowledge worth questioning, but a modest promise is not a trust transfer.', '{companion} saw Pell request originals rather than copies. That choice makes sense beside the torn page and missing will. Her pension explains financial hope; the surviving carbon copy identifies a different recipient of the larger sums.'],
    doctor: ['{doctor} admits a careless certificate, yet Cecily had written several accountability letters. The professional complaint was one dispute among many, not proof that the missing papers concerned medical care.', '{doctor}\'s complaint stayed where it could still expose the mistake. The killer targeted the will and trust page instead. That selective removal weakens a reputation-only motive while strengthening the question of who needed the financial record gone.'],
    foreman: ['{foreman} diverted a repair allowance to wages, while the new trust would support injured workers. Those two facts complicate an assumption that every workplace grievance opposed the will.', '{foreman} was told there was no money for workers while transfers went to the adviser\'s practice. Her unauthorized allowance is not the missing fortune. The carbon page distinguishes the scale and recipient of the thefts.'],
    journalist: ['{journalist} knew Cecily asked a bank contact to review trustee transactions. The planned expose was deception about an invitation, but its subject was a financial concern already raised by Cecily.', '{journalist} recorded Pell insisting on the old will before the announcement. That insistence fits the missing new document\'s threat to the trustee. The reporter\'s secrecy concerns a source and a story, not ownership of the transferred money.'],
    cousin: ['{cousin} heard Cecily say the family could manage without Pell. The refused loan and sold keepsake made need look like motive, while that statement concerns an adviser\'s position rather than cutting off the heirs.', '{cousin} saw the duplicate before the alarm. That timing helps establish an existing document, not a replacement invented after the death. The keepsake lie explains embarrassment but does not account for the carbon transfers or study meeting.'],
  },
};
