// Required roles carry the solving clues; optional roles add motives and corroboration.
const clueRound = (clues, instructions) => ({ clues, instructions });

function character(id, name, role, publicBlurb, backstory, secrets, motive, rounds, optional = false) {
  return { id, name, role, publicBlurb, backstory, secrets, motive, rounds, optional, guest: '', guestNote: '' };
}

const witchStory = {
  schemaVersion: 1,
  title: 'The Ashes of Mercy Hollow',
  setting: 'Mercy Hollow, a fictional New England village, autumn 1692. Rain lashes the meetinghouse while accusations of witchcraft divide the town. Inspired by the atmosphere of the Salem trials, not a retelling of real victims or events.',
  intro: 'Magistrate Elias Ward has called an extraordinary meeting. Tomorrow he intends to suspend the witch hearings and examine the land deeds taken from accused families. Tonight he will hear every objection.\n\nThe village midwife has been blamed for a failed harvest. The minister has been accused of hiding testimony. Someone has nailed a black ribbon to the meetinghouse door.\n\nWard places a sealed packet on the table. "A frightened village can be led anywhere," he says. "Before dawn, we shall discover who has been leading ours." A gust rattles the shutters. Nobody laughs.',
  victim: { name: 'Magistrate Elias Ward', description: 'An exacting magistrate who has begun to distrust the accusations he once allowed.' },
  rounds: [
    {
      title: 'Round 1 - The Black Ribbon',
      narration: 'Ward takes his packet into the small records room to compare it with the town ledger. A little later the minister opens the door and calls for help. Ward lies motionless beside the overturned writing table. The packet is gone.\n\nPinned to his coat is a scrap of paper: "The hollow takes what it is owed."\n\nOutside, the road has become a river of mud. You must remain in the meetinghouse until the constable returns at dawn. Is this a witch taking revenge, or a person who needs you to believe in one?',
      publicText: 'Ward is dead in the records room. His sealed packet is missing. A threatening note invokes the hollow. Establish who entered the room and what the packet contained.',
      hostNotes: 'Allow about 15 minutes. Accusations of witchcraft are part of the setting, not reliable evidence. No player needs to pretend to be a real historical victim.',
    },
    {
      title: 'Round 2 - A Confession Without a Voice',
      narration: 'A damp bundle has been pushed beneath the meetinghouse door. It contains a supposed confession from a woman already held in another town. She claims that her spirit killed Ward.\n\nBut the jail register inside the bundle shows that she was watched all evening. Ward had underlined a sentence in his own notes: "Fear is useful to the owner of a borrowed signature."\n\nIn the hearth, someone finds half a scorched deed. The buyer is not named, but a payment column survives.',
      publicText: 'The supernatural confession proves nothing. The surviving deed records money diverted into a private account. Ward was investigating document fraud, not magic.',
      hostNotes: 'Give another 15 minutes. Ask what earthly benefit follows from each accusation. Optional characters add village disputes; the four required roles have the evidence needed to solve the crime.',
    },
    {
      title: 'Round 3 - The Seal in the Ashes',
      narration: 'The rain eases. In Ward\'s open notebook, the final entry reads: "The clerk has collected payments for three deeds the council never approved. I have demanded the originals tonight."\n\nA damaged seal is recovered from the hearth. Its unusual missing star matches the town seal used on the threatening note and forged confession. A brass fragment beside it fits a newly broken chain worn by the clerk.\n\nThe minister produces a page rescued before the meeting. The same false witness phrase appears in both the confession and a draft in the clerk\'s handwriting. You no longer need a ghost to explain the crime.',
      publicText: 'Ward named the clerk in his notebook. A missing star links the forged documents to the town seal. A brass fragment matches the clerk\'s broken chain. Compare those findings with the testimony about entry to the records room.',
      hostNotes: 'Final discussion, then voting. Do not require a confession from the killer. The evidence can convict even if the killer lies.',
    },
  ],
  finale: {
    narration: 'At dawn the constable will take testimony, not rumors. Name the person who killed Ward, say what they stood to lose, and explain which evidence separates guilt from mere suspicion.',
    votePrompt: 'Who murdered Magistrate Elias Ward?',
  },
  solution: {
    killerId: 'clerk',
    explanation: 'Jonah Pike, the town clerk, killed Ward to conceal fraudulent land transfers. Pike had turned the panic into profit: he falsified testimony against families whose land he wanted, then diverted payments through a private account. Ward discovered the unapproved deeds and demanded the originals.\n\nPike followed Ward into the records room. Their confrontation ended in murder. He removed the packet and planted a supernatural threat, then tried to burn the deeds and the damaged town seal. The forged confession was another attempt to send the village back toward an imaginary enemy.\n\nMara saw Pike enter after Ward; Ruth heard the discussion turn to missing payments; Nathaniel preserved a draft in Pike\'s hand. The notebook, seal and broken chain connect motive, forgery and presence. The other villagers concealed debts, family ties and false statements, but none of those secrets explains all three links. No witch killed Ward, and the accused villagers were not responsible for their persecutors\' crimes.',
    revealNarration: 'Nathaniel places the rescued draft beside the confession. Ruth lays the brass fragment against Jonah Pike\'s chain. Mara reads Ward\'s final entry aloud.\n\nFor the first time that night, the clerk has no words prepared.\n\nThe dawn light reaches the black ribbon. It is only cloth. The thing that haunted Mercy Hollow was fear, and the person who learned to sell it.',
  },
  characters: [
    character('clerk', 'Jonah Pike', 'The Town Clerk',
      'Keeper of deeds, testimony and the meetinghouse keys. You insist that the village needs order.',
      'You began by altering a payment entry to cover a debt. Soon accusations allowed you to acquire land cheaply. Ward was about to expose the entire scheme.',
      ['YOU ARE THE KILLER. You killed Ward during a confrontation in the records room, stole his packet and staged a supernatural warning.', 'You forged accusations and diverted land payments. Your brass chain broke in the records room.'],
      'Avoid prosecution and keep the land and money obtained through forged records.',
      [
        clueRound(['Ward summoned you to bring the original deeds.', 'The records-room door was not locked; others could enter.'], 'You may lie. Suggest that Ward angered an accused family. Do not reveal future clues.'),
        clueRound(['The scorched payment column is from your private accounts.', 'Your forged confession repeats a phrase from an earlier draft.'], 'Question the accuracy of everyone\'s memories. Offer a worldly explanation for the accounts without admitting fraud.'),
        clueRound(['Ward\'s notebook names you. The damaged seal and broken chain connect you to the room and the forged papers.'], 'You can challenge individual clues, but cannot erase the host\'s public findings. Decide whether to maintain your story or admit the scheme after the vote.'),
      ]),
    character('midwife', 'Ruth Bell', 'The Accused Midwife',
      'A respected healer whose ordinary work has become the subject of ugly rumors.',
      'Ward once allowed testimony against your sister. You came to demand that he clear her name. You are tired of having grief treated as guilt.',
      ['You wrote Ward an angry letter, but did not kill him.', 'You hid your sister\'s whereabouts from the council to keep her safe.'],
      'Get your sister cleared and stop the hearings; anger at Ward makes you an easy suspect.',
      [
        clueRound(['Before his death, Ward asked you to identify who had been pressuring accused families to sell.', 'You heard a man in the records room say, "Those payments were mine to collect."'], 'Share what you heard. You may withhold your sister\'s location, but do not invent evidence.'),
        clueRound(['Ward showed you a deed whose named seller had never agreed to sell.', 'The seller said {clerk} collected the payment and kept the original.'], 'Separate your personal anger from the evidence. Explain why the land transactions matter.'),
        clueRound(['You saw {clerk} arrive with an intact brass chain. It is now broken.', 'The recovered fragment has the same squared clasp you noticed earlier.'], 'Connect the chain to the public finding. Your letter was a demand for justice, not a threat of murder.'),
      ]),
    character('minister', 'Nathaniel Reed', 'The Doubting Minister',
      'You once preached certainty. Tonight you seem less sure of everything.',
      'You repeated accusations without checking them. Ward offered a chance to correct the record; admitting your mistake may cost your position.',
      ['You concealed a letter warning that two testimonies had been copied.', 'You entered the records room and discovered the body; you did not kill Ward.'],
      'Protect your reputation, or finally tell the truth about the hearings.',
      [
        clueRound(['You found Ward beside the table and immediately called for help.', 'The threatening note bears the town seal, not an occult mark.'], 'Describe the discovery clearly. Admit the letter if pressed.'),
        clueRound(['You rescued a discarded draft from {clerk}\'s desk before the meeting.', 'It includes a strange witness phrase you recognize in the newly delivered confession.'], 'Share the matching phrase. A document is evidence of a person writing, not a spirit acting.'),
        clueRound(['The draft is in {clerk}\'s handwriting.', 'The missing star on the recovered seal also appears on the draft and threatening note.'], 'Show how the documents connect. Make clear that your earlier certainty was not proof.'),
      ]),
    character('witness', 'Mara Vale', 'The Recanting Witness',
      'Your testimony helped start the panic. You have come to withdraw it.',
      'Someone rewarded your family after you repeated a story about an accused neighbor. Ward promised protection if you identified who dictated it.',
      ['Your original testimony was false.', 'You accepted money because your family was hungry; you regret what followed.'],
      'Avoid punishment for false testimony and protect your family.',
      [
        clueRound(['You saw {clerk} enter the records room after Ward. You stayed near the corridor until the minister arrived.', 'You saw nobody else enter between them.'], 'Give your timeline. Your embarrassment is not a reason to hide the truth.'),
        clueRound(['{clerk} dictated your original accusation and arranged the payment.', 'Ward\'s missing packet included your signed retraction.'], 'Admit how the testimony was manufactured. It explains why somebody wanted the packet gone.'),
        clueRound(['You saw {clerk} leave holding a packet beneath his coat.', 'He asked you not to mention the corridor, saying the village would blame you instead.'], 'Compare his pressure with the notebook and seal. Do not let fear decide your vote.'),
      ]),
    character('miller', 'Gideon Frost', 'The Indebted Miller',
      'Your mill feeds the village, but the grain accounts do not balance.',
      'You sold some grain twice on paper to stave off bankruptcy. Ward intended to inspect your books next week.',
      ['You falsified grain receipts, not witch testimony.', 'You argued with Ward in public and now fear that everyone remembers.'],
      'Keep your mill and conceal a lesser fraud.',
      [
        clueRound(['You argued with Ward about grain before he entered the records room.'], 'Own the argument, but explain it concerned grain.'),
        clueRound(['A debt receipt shows you paid {clerk} a records fee twice.'], 'Offer the receipt as corroboration, not the only proof.'),
        clueRound(['The private payment column includes your mill\'s name; it was not a lawful council charge.'], 'Help distinguish your dishonest accounts from the murder scheme.'),
      ], true),
    character('seamstress', 'Esther Finch', 'The Seamstress',
      'You know which households buy black ribbon and which pretend they do not.',
      'You have been helping an accused friend leave town. Your deliveries gave you a glimpse of many private meetings.',
      ['You supplied ordinary black ribbon to three households.', 'You hid a traveling cloak for a friend fleeing the accusations.'],
      'Protect your friend and avoid being accused yourself.',
      [
        clueRound(['The ribbon on the door is common mourning ribbon, not a witch\'s token.'], 'Challenge superstition without claiming to know the killer.'),
        clueRound(['You delivered a coat to {clerk}; there were land receipts on his table.'], 'Discuss what you saw without guessing what every document meant.'),
        clueRound(['The clerk asked you to repair a chain clasp after the meeting had begun, but you never did.'], 'Offer the request as supporting evidence.'),
      ], true),
    character('innkeeper', 'Tobias Wren', 'The Innkeeper',
      'The village argues in your common room. You remember who pays.',
      'You sheltered an accused traveler and lied about it to the council. Ward had quietly paid for the traveler\'s food.',
      ['You lied to protect a guest.', 'You owe Ward money and were embarrassed to ask for more time.'],
      'Save your inn and protect the person hiding there.',
      [
        clueRound(['Ward recently paid to shelter an accused traveler; his views were changing.'], 'Explain his change without revealing your guest\'s hiding place.'),
        clueRound(['{clerk} boasted that the next land sale would settle his debts.'], 'Share the boast as a possible motive, not a verdict.'),
        clueRound(['The account named on the burnt deed is the one {clerk} used to settle his inn bill.'], 'Corroborate the money trail already found by the required roles.'),
      ], true),
    character('schoolmaster', 'Abigail Moss', 'The Schoolmaster',
      'You teach letters to children and quietly to several adults.',
      'You helped Mara write her retraction. You fear that telling the truth will make the school a target.',
      ['You helped write the retraction in Ward\'s missing packet.', 'You concealed an anonymous threat against the school.'],
      'Protect the school and your pupils from retaliation.',
      [
        clueRound(['Mara came to the meeting intending to correct her testimony, not to repeat it.'], 'Support her without speaking for her.'),
        clueRound(['The confession\'s wording is unusually similar to village court forms.'], 'Discuss the wording; avoid treating intuition as proof.'),
        clueRound(['You saw Ward annotate the retraction with "Ask Pike about the payments."'], 'Add corroboration to Ward\'s public notebook entry.'),
      ], true),
  ],
};

const farmStory = {
  schemaVersion: 1,
  title: 'Footsteps Above Blackthorn Farm',
  setting: 'Blackthorn Farm, a fictional Alpine foothill settlement, winter 1923. An isolated farm, unexplained footsteps and a stranger nobody can find evoke the unsolved Hinterkaifeck case. This story uses invented people and an invented solution.',
  intro: 'Otto Hartmann has invited a small gathering to Blackthorn Farm to settle its future. He says the proposed sale contains a lie, and tonight he will name it.\n\nFor a week, the household has heard footsteps above the ceiling. Food has gone missing. A fresh track crosses the snow toward the woods, but nobody recalls a visitor.\n\nOtto refuses to abandon the house. "Someone wants me frightened enough to sign," he says. The evening meal is laid out. A blizzard erases the lane behind you.',
  victim: { name: 'Otto Hartmann', description: 'Owner of Blackthorn Farm. Stubborn, suspicious, and about to reject a lucrative land sale.' },
  rounds: [
    {
      title: 'Round 1 - The Empty Chair',
      narration: 'Otto goes to the workshop to retrieve the sale map. When he fails to return, the housekeeper and mechanic go looking. They find him dead beside his desk. A folded map has been torn in half; a stranger\'s cap lies by the outer door.\n\nAbove the workshop ceiling, a floorboard creaks. You call out. No answer.\n\nThe storm makes the road impassable. Search the accounts, compare your stories, and decide whether the stranger was real or merely useful.',
      publicText: 'Otto is dead in the workshop. A torn sale map and an unfamiliar cap suggest an intruder. The road is blocked; the killer may be among the invited guests.',
      hostNotes: 'Give about 15 minutes. There are no attacks on children and no graphic reenactments. The farm is an atmosphere, not a recreation of the historical case.',
    },
    {
      title: 'Round 2 - A Bed Above the Beams',
      narration: 'A loose panel reveals a narrow attic room above the workshop. There is a blanket, an old cup and sketches of the farm boundary. The supposedly unknown visitor had somewhere to sleep.\n\nAmong the sketches is a second version of the sale map. It leaves the north spring outside the farmhouse boundary. On Otto\'s desk, a letter says the spring is what makes the buyer\'s offer so valuable.\n\nA frightening visitor might be only the first half of a very ordinary land swindle.',
      publicText: 'The attic hiding place contains boundary sketches. The sale map diverts the valuable north spring. Find who knew the hidden room and who controlled the maps.',
      hostNotes: 'Another 15 minutes. The optional roles add local rumors and debts, but the main witnesses can establish access, motive and the timeline alone.',
    },
    {
      title: 'Round 3 - The Line That Moved',
      narration: 'The signed survey ledger is found beneath Otto\'s desk. It records a payment to Leon Adler for "amended north boundary," followed by Otto\'s note: "Adler moved the line. No sale until he answers."\n\nA brass button recovered from the workshop matches a fresh gap in Adler\'s distinctive survey coat. Clara produces the original plan showing that the spring belongs to the farm. Marta confirms she saw Adler leave the workshop after Otto went inside; Emil confirms the concealed stairs were accessible from Adler\'s measuring room.\n\nThe stranger\'s cap now seems less convincing than the surveyor\'s missing button.',
      publicText: 'The ledger names Adler as the paid author of the altered boundary. Otto challenged him. A missing coat button and witness testimony place Adler in the workshop; the hidden stairs explain the staged haunting.',
      hostNotes: 'Final discussion, then voting. Use the testimony and ledger together; the cap and footsteps alone are not proof of an outsider.',
    },
  ],
  finale: {
    narration: 'Snow presses against the windows, but the tracks inside the house are clearer now. Name Otto\'s killer and explain why someone needed both a false map and a false intruder.',
    votePrompt: 'Who murdered Otto Hartmann at Blackthorn Farm?',
  },
  solution: {
    killerId: 'surveyor',
    explanation: 'Leon Adler killed Otto after Otto discovered that he had moved the north boundary on the sale plan. Adler was being paid secretly by the buyer to exclude the spring from the farmhouse parcel. He had used the attic room during earlier visits to stage an unsettling presence, hoping Otto would accept a quick sale and leave.\n\nOtto instead compared the maps, found the secret payment and called the gathering to confront Adler. Adler met him in the workshop; the confrontation ended in murder. He tore the map and left a stranger\'s cap to reinforce the outsider story. His coat caught on the desk, leaving a brass button.\n\nClara has the lawful boundary, Marta has Adler\'s departure from the workshop, and Emil knows the concealed stair access. The ledger supplies the motive and authorship; the button corroborates physical presence. The others have their own debts, thefts and ambitions, but only Adler connects the manipulated map, hidden room and fatal confrontation. The mysterious footsteps were human. This fictional solution makes no claim about who committed the real Hinterkaifeck murders.',
    revealNarration: 'Clara flattens the original plan. Emil places the button on its north boundary. Marta looks at the gap in Leon Adler\'s coat.\n\n"You wanted us watching the forest," she says, "so we would never look at the line you moved."\n\nAbove the room, the loose floorboard gives one final creak. Nobody calls it a ghost this time.',
  },
  characters: [
    character('surveyor', 'Leon Adler', 'The Land Surveyor',
      'A polished professional who says the farm\'s boundaries are complicated.',
      'The buyer paid you to redraw the boundary around the north spring. Otto found the earlier map, and your respectable career was about to unravel.',
      ['YOU ARE THE KILLER. You killed Otto in the workshop after he confronted you about the altered boundary.', 'You used the attic room to frighten the household into selling. The stranger\'s cap was staged.'],
      'Keep the secret payment and avoid exposure as a fraudulent surveyor.',
      [
        clueRound(['Otto called you to discuss the north boundary before dinner.', 'A brass button is missing from your survey coat.'], 'You may lie. Attribute the missing button to fieldwork and encourage discussion of the supposed intruder.'),
        clueRound(['Your draft maps were stored in the attic room.', 'You told Otto the room was inaccessible; that was false.'], 'Claim the sketches were old and ordinary. Challenge the sale motives of the other guests.'),
        clueRound(['The signed ledger and Otto\'s annotation expose your payment.', 'Marta saw you leave; Emil can explain your access to the attic.'], 'You may defend yourself but cannot undo the public discoveries. Save any confession for the reveal.'),
      ]),
    character('heir', 'Clara Hartmann', 'The Reluctant Heir',
      'Otto\'s adult niece wants a future beyond the farm, but also wants a fair sale.',
      'You secretly contacted another buyer. Otto called that a betrayal, though you intended to pay his debts rather than abandon him.',
      ['You would inherit the farm, giving you an obvious motive.', 'You hid the original boundary plan because you feared it would be destroyed.'],
      'Resolve the debts and stop being treated as a child, without losing the farm dishonestly.',
      [
        clueRound(['Otto said the offered price made no sense unless someone was concealing the value of the spring.', 'The torn map is not the plan you remember from childhood.'], 'Discuss the financial motive. Admit the other buyer if asked.'),
        clueRound(['Your original plan puts the north spring inside the farm boundary.', 'The amended plan is signed by {surveyor}.'], 'Show the original. You can prove the map changed without knowing the killer yet.'),
        clueRound(['Otto\'s handwritten note on your plan says he would confront {surveyor} that evening.', 'Your inheritance depends on the truthful boundary, not the false one.'], 'Connect the challenge to the ledger and timeline.'),
      ]),
    character('housekeeper', 'Marta Weiss', 'The Housekeeper',
      'You returned after a previous worker left because of the footsteps.',
      'You took food to a struggling neighbor and let the household blame the missing supplies on a stranger. Now a harmless lie makes a real crime harder to untangle.',
      ['Some missing food was your doing, not a hidden visitor.', 'You had threatened to leave because Otto withheld wages.'],
      'Recover your wages and conceal the food theft.',
      [
        clueRound(['You watched Otto enter the workshop from the kitchen window.', 'A few minutes later, you saw {surveyor} leave its side door, alone.'], 'Give the sighting accurately. The food secret does not make you responsible for every odd event.'),
        clueRound(['You found a cup in the attic with the same chipped handle as one from the surveyor\'s measuring room.', 'The hidden blanket appeared after {surveyor}\'s last overnight visit.'], 'Share the supporting links. Do not claim a cup alone proves murder.'),
        clueRound(['You remained at the window until Emil arrived; no outsider crossed the courtyard in that interval.', 'The coat worn by the departing figure was {surveyor}\'s survey coat.'], 'Complete the timeline and explain why you initially hesitated.'),
      ]),
    character('mechanic', 'Emil Rauch', 'The Farm Mechanic',
      'You maintain the equipment and know every awkward corner of the house.',
      'You pawned spare parts without Otto\'s permission. He discovered it, and you expected dismissal tonight.',
      ['You stole spare parts but did not harm Otto.', 'You repaired the concealed attic stair last month at the surveyor\'s request.'],
      'Keep your livelihood and avoid prosecution for theft.',
      [
        clueRound(['You found Otto with Marta and raised the alarm.', 'The side door had not been forced. The intruder story does not require a broken lock.'], 'Explain the scene, keeping evidence separate from speculation.'),
        clueRound(['The attic stair starts in the measuring room used by {surveyor}.', 'You repaired it at his request; he knew it worked.'], 'Reveal the repair even though Otto never authorized it.'),
        clueRound(['The recovered button matches the brass buttons on {surveyor}\'s survey coat.', 'You saw Otto leave the house carrying an intact map; it was torn during the workshop encounter.'], 'Link the button, access and timing. Your parts theft is a different offense.'),
      ]),
    character('neighbor', 'Greta Baum', 'The Boundary Neighbor',
      'You have argued with Otto about fences for years.',
      'You moved a fence post to help your livestock reach water. You fear the sale survey will expose it.',
      ['You moved a fence post, not the north spring boundary.', 'You came expecting Otto to threaten a lawsuit.'],
      'Keep access to water and avoid a costly dispute.',
      [
        clueRound(['The footprints at the woods are older than tonight\'s fresh snow.'], 'Question the supposed visitor without pretending to identify the tracks.'),
        clueRound(['The spring is far more valuable than the disputed pasture.'], 'Explain why a buyer might want the north boundary altered.'),
        clueRound(['You saw {surveyor} measuring near the attic window on an earlier visit.'], 'Corroborate his familiarity with the building.'),
      ], true),
    character('teacher', 'Ansel Vogel', 'The Village Teacher',
      'You helped Otto read the small print in the sale offer.',
      'You were paid to summarize a contract and missed an important clause. Otto believed you were careless, not corrupt.',
      ['You hid your mistake because you feared losing trust.', 'You borrowed money from Clara without telling Otto.'],
      'Repair your reputation and repay the loan.',
      [
        clueRound(['Otto\'s letter said he intended to delay, not complete, the sale tonight.'], 'Explain why an impatient buyer might be angry.'),
        clueRound(['One clause assigns spring access according to the amended map.'], 'Translate the clause plainly for the others.'),
        clueRound(['The buyer\'s correspondence describes a fee paid to the surveyor, separate from Otto\'s bill.'], 'Support the money trail found in the ledger.'),
      ], true),
    character('postmaster', 'Frieda Kern', 'The Postmaster',
      'You brought a delayed parcel through the snow and stayed for supper.',
      'You opened a letter addressed to the farm, hoping it concerned a relative\'s debt. It did not, and you resealed it badly.',
      ['You opened private mail.', 'You hid the delay because the letter warned Otto of the buyer\'s reputation.'],
      'Avoid dismissal for interfering with mail.',
      [
        clueRound(['The parcel delivered today contained map paper, not a weapon or strange charm.'], 'Describe the delivery without embellishment.'),
        clueRound(['A letter warned Otto to compare the maps before signing anything.'], 'Admit you read it; it explains his investigation.'),
        clueRound(['The amended-map invoice was mailed to {surveyor}, not to Clara.'], 'Add supporting authorship evidence.'),
      ], true),
    character('buyeragent', 'Kaspar Lenz', 'The Buyer\'s Agent',
      'You want signatures before the storm ends and prices change.',
      'Your employer told you only that the spring would be profitable. You did not understand why the new map was different, but you chose not to ask.',
      ['You pressured Otto to sell quickly.', 'You knew there was a separate payment to the surveyor and concealed it.'],
      'Earn your commission and protect your employer.',
      [
        clueRound(['Otto rejected your deadline before dinner.'], 'Admit the pressure without inventing an alibi for others.'),
        clueRound(['The proposed sale gives your employer control of the spring under the amended plan.'], 'Explain the commercial stakes.'),
        clueRound(['Your employer\'s letter calls {surveyor} the author of the amendment.'], 'Reveal what you withheld; ambition does not make every agent a murderer.'),
      ], true),
    character('musician', 'Lotte Brandt', 'The Traveling Musician',
      'You were stranded on the lane and invited in before the storm.',
      'You once used another name while escaping a debt. An unknown cap and an unfamiliar face make you a convenient outsider.',
      ['You are not using your birth surname.', 'The cap is not yours; you have seen it in the farm\'s spare-clothes basket.'],
      'Avoid attention from a creditor and stop the room blaming the newest arrival.',
      [
        clueRound(['The supposedly strange cap was already in the house before dinner.'], 'Challenge the planted-object story.'),
        clueRound(['You heard ordinary movement above the measuring room before the alarm.'], 'Describe the sound, but do not invent a sighting.'),
        clueRound(['You remember {surveyor} removing a spare cap from the basket earlier.'], 'Offer a corroborating observation, not the sole decisive clue.'),
      ], true),
  ],
};

const inheritanceStory = {
  schemaVersion: 1,
  title: 'The Last Will at Briar House',
  setting: 'Briar House, a fictional New England manufacturing town, 1893. A respectable household hides fierce arguments over money. Inspired loosely by the atmosphere surrounding the Borden case, with invented characters, crime and solution.',
  intro: 'Cecily Harcourt has gathered family, staff and advisers at Briar House for an announcement. She is changing her will and dismissing the person who has been managing her accounts.\n\nA charitable trust will receive much of her fortune. Nobody knows how much remains for the family. The new document waits in her study; the old one is displayed in the drawing room.\n\nAt eight, Cecily says she will fetch the final account book. "Respectability," she remarks, "is an expensive disguise." The front gate is locked for the evening. Everyone has a reason to worry.',
  victim: { name: 'Cecily Harcourt', description: 'Widowed owner of a textile fortune, determined to put her accounts and household in order.' },
  rounds: [
    {
      title: 'Round 1 - The Bell That Rang Too Late',
      narration: 'The study bell rings, but no footsteps follow. The house secretary opens the door and calls everyone inside. Cecily is dead beside the desk. The new will is missing, and the account book is open to a page torn down the middle.\n\nThe family solicitor says he heard the bell from the drawing room and never entered the study. Cecily\'s nephew says the will would have ruined him. Her daughter says the house has been ruined for years.\n\nThe police are delayed by a fire blocking the bridge. Until they arrive, the drawing room becomes its own court.',
      publicText: 'Cecily is dead. The new will is missing and an account page was torn. The study bell rang after someone inside the room must have pulled it. Establish the sequence, not just who inherits.',
      hostNotes: 'About 15 minutes. This is a non-graphic adult household mystery. A bell heard in another room is not automatically a reliable alibi.',
    },
    {
      title: 'Round 2 - Two Wills and One Lie',
      narration: 'A duplicate of the new will turns up in the secretary\'s correspondence tray. The family still inherits generously. The person who loses most is not an heir: the solicitor is removed as trustee and ordered to repay unexplained withdrawals.\n\nCecily\'s daughter brings out a letter her mother wrote that afternoon: "Pell must return what he has taken, or tomorrow I go to the bank."\n\nThe old will was a distraction. The torn account page may tell you what the killer actually feared.',
      publicText: 'The new will does not disinherit the family. It removes the solicitor as trustee. Cecily intended to report unexplained withdrawals to the bank.',
      hostNotes: 'Another 15 minutes. Let the household secrets surface. Keep the money investigation distinct from the family\'s dislike of Cecily.',
    },
    {
      title: 'Round 3 - The Carbon Copy',
      narration: 'The secretary finds a carbon copy of the torn account page. It records money transferred to Edmund Pell\'s private practice. Cecily had circled the total and written, "Confront Pell tonight."\n\nThe housekeeper saw Pell come out of the study while the bell was still sounding, before the alarm was raised. The secretary confirms that he personally collected the new will earlier that evening. Cecily\'s daughter produces the appointment note giving Pell the private meeting he denied.\n\nPell\'s claim that he never entered now conflicts with three independent pieces of evidence. The missing will could not remove the duplicate, and the torn page could not remove its copy.',
      publicText: 'The carbon copy names Edmund Pell\'s private practice as recipient of the missing money. His appointment, collection of the will and exit from the study contradict his claimed absence. The bell did not give him an alibi.',
      hostNotes: 'Final discussion, then voting. All decisive evidence is available through required characters and public narration, even with only four players.',
    },
  ],
  finale: {
    narration: 'The front gate opens as the constable arrives. Before anyone hands over a name, explain the money trail and the false timeline. A family quarrel is not enough. Which person needed the new will and its accounts to disappear?',
    votePrompt: 'Who murdered Cecily Harcourt at Briar House?',
  },
  solution: {
    killerId: 'solicitor',
    explanation: 'Edmund Pell, the family solicitor, killed Cecily to hide withdrawals from the trust he managed. Cecily\'s new will still provided for her family, but removed Pell as trustee and required an accounting. She intended to report him to the bank the next morning.\n\nPell collected the will and met Cecily privately. When she demanded repayment, their confrontation ended in murder. He took the will and tore the incriminating account page. He used the study bell before leaving to create a misleading time marker, then claimed he had heard it from the drawing room and never entered the study.\n\nAda saw him leave before the bell finished sounding. Iris recorded his collection of the document and preserved the carbon account copy. Beatrice has both Cecily\'s letter and the appointment note. Those independent sources establish money, access and the false timeline. A carbon copy and duplicate will survived the destruction of the originals. The family\'s resentment, staff thefts and other deceptions explain red herrings, not the full chain. This invented answer is not a claim about the guilt of anyone in the real Borden case.',
    revealNarration: 'Iris lays the carbon page beneath the drawing-room lamp. Beatrice reads the appointment. Ada repeats the order of the footsteps and the bell.\n\nEdmund Pell reaches for the old will. Nobody lets him take it.\n\nCecily\'s last accounting is complete. In a house devoted to appearances, the truth survived because somebody made a copy.',
  },
  characters: [
    character('solicitor', 'Edmund Pell', 'The Family Solicitor',
      'A trusted adviser who knows every signature in the household.',
      'You withdrew trust money to support your failing practice. Cecily found the transfers and would not accept your promise to repay them later.',
      ['YOU ARE THE KILLER. You killed Cecily during the private study meeting, took the new will and tore the account page.', 'You rang the study bell before leaving and lied about hearing it from the drawing room.'],
      'Conceal the withdrawals and avoid losing your practice and freedom.',
      [
        clueRound(['Cecily insisted you meet her before the announcement.', 'You claimed you had not entered the study at all.'], 'You may lie. Emphasize the nephew\'s debts and the daughter\'s arguments.'),
        clueRound(['The duplicate will removes you as trustee but leaves the family comfortable.', 'Cecily\'s bank letter threatens your career.'], 'Claim the withdrawals were authorized fees. Do not pretend the public will says something else.'),
        clueRound(['The carbon page, appointment and witness timeline expose your account and false alibi.'], 'Challenge interpretations if you wish, but do not erase discovered evidence. Decide what to say after the vote.'),
      ]),
    character('daughter', 'Beatrice Harcourt', 'The Estranged Daughter',
      'You have returned to a home where every courtesy sounds like a criticism.',
      'You wanted control of your own inheritance, not another trust administered by Pell. You argued loudly with your mother this afternoon and regretted it.',
      ['You threatened to leave the family, not to kill Cecily.', 'You hid a letter from your mother while deciding whether to expose the accounts publicly.'],
      'Gain independence and settle years of resentment.',
      [
        clueRound(['Cecily said the announcement would concern her adviser as much as her family.', 'She had a private appointment before the drawing-room gathering.'], 'Admit the argument, but do not let it replace the timeline.'),
        clueRound(['Your mother\'s letter says, "Pell must return what he has taken, or tomorrow I go to the bank."', 'The new will still gives you an inheritance.'], 'Read the letter. Explain why disinheritance is the wrong motive.'),
        clueRound(['The appointment note names {solicitor} and places him in the study before the bell.', 'Cecily wrote that she wanted the meeting witnessed later by the secretary.'], 'Share the note even though you wanted a private resolution.'),
      ]),
    character('housekeeper', 'Ada March', 'The Housekeeper',
      'You run Briar House and hear more than the family realizes.',
      'You quietly took household money to help your brother. Cecily noticed a shortfall, and you feared dismissal. You know a small theft can look much larger tonight.',
      ['You took a small household sum, not trust withdrawals.', 'You delayed admitting what you saw because you feared an investigation of your own accounts.'],
      'Keep your job and protect your brother.',
      [
        clueRound(['You were near the study corridor before the alarm.', 'You saw {solicitor} leave the study before the bell finished ringing.'], 'State the order carefully. Do not hide a useful sighting to protect a lesser secret.'),
        clueRound(['The study bell rings for several moments after it is pulled.', 'A person can already be in the corridor while its sound continues.'], 'Explain why the bell cannot establish where Pell was at its start.'),
        clueRound(['{solicitor} carried a folded legal document when he left.', 'You saw no other person enter between Cecily\'s meeting and Iris discovering the body.'], 'Complete the access timeline and admit your own theft separately.'),
      ]),
    character('secretary', 'Iris Shaw', 'The House Secretary',
      'You make copies, manage correspondence and remember what people ask you to forget.',
      'You had accepted a job elsewhere. Cecily accused you of abandoning the household, then unexpectedly offered a generous reference.',
      ['You planned to leave without telling the family.', 'You kept copies of important accounts because Cecily instructed you to.'],
      'Leave with your reputation intact and stop being blamed for missing papers.',
      [
        clueRound(['You found Cecily after the bell.', 'Earlier, {solicitor} signed your receipt book when he collected the new will for the meeting.'], 'Share the receipt. A missing document did not necessarily vanish after the death.'),
        clueRound(['Your correspondence tray contains a duplicate will removing Pell as trustee.', 'The family is not disinherited.'], 'Produce the duplicate before anyone builds an accusation on a false premise.'),
        clueRound(['Your carbon copy records transfers to Edmund Pell\'s private practice.', 'Cecily wrote "Confront Pell tonight" beside the total.'], 'Read the entry aloud and connect it to the appointment and corridor sighting.'),
      ]),
    character('nephew', 'Felix Harcourt', 'The Reckless Nephew',
      'Your debts are the least secret secret at Briar House.',
      'You expected your aunt to rescue you again. She refused, and you told everyone the new will must have cut you out.',
      ['You exaggerated what you knew about the will.', 'You borrowed money from a guest under a false promise of repayment.'],
      'Avoid ruin and keep your family support.',
      [
        clueRound(['You never actually read the new will.'], 'Admit your disinheritance story was a guess.'),
        clueRound(['The duplicate still provides enough money to address your debts.'], 'Recognize that your strongest supposed motive was mistaken.'),
        clueRound(['Pell encouraged you to complain about the will before supper.'], 'Describe his encouragement without claiming it proves everything.'),
      ], true),
    character('companion', 'Sylvia Grey', 'The Widow\'s Companion',
      'You shared Cecily\'s quiet hours, but the family resents your closeness.',
      'Cecily promised you a small pension. You kept that promise secret because the family already believed you were seeking her fortune.',
      ['You hoped to receive a pension.', 'You concealed a letter about leaving the house after the announcement.'],
      'Secure a modest future and escape the household\'s suspicion.',
      [
        clueRound(['Cecily said she wanted to repay loyalty, not punish her family.'], 'Challenge the rumors of wholesale disinheritance.'),
        clueRound(['She told you the accounts had become "someone else\'s purse."'], 'Share her concern but do not pretend you knew the details.'),
        clueRound(['You saw Pell request that Iris bring him only originals, not copies.'], 'Explain why the survival of copies might surprise him.'),
      ], true),
    character('doctor', 'Dr. Rowan Hale', 'The Household Physician',
      'You have been urging Cecily to work less and rest more.',
      'You certified a factory worker fit before listening properly to their complaint. Cecily had learned of it and demanded an explanation.',
      ['You gave a careless certificate and feared a professional complaint.', 'Cecily intended to replace you, though she had not yet done so.'],
      'Protect your professional reputation.',
      [
        clueRound(['Cecily was alert before entering the study; do not dismiss the death as an expected illness.'], 'Avoid claiming medical details beyond what you can observe.'),
        clueRound(['She had written several letters about accountability, not just one complaint against you.'], 'Admit your own mistake without making it an excuse to accuse others.'),
        clueRound(['The complaint about you remained on her desk; the account page and will were specifically targeted.'], 'Discuss selective removal as a clue to motive.'),
      ], true),
    character('foreman', 'Nora Bellamy', 'The Factory Foreman',
      'You brought a petition asking for better conditions at the mill.',
      'You exaggerated a repair bill to fund emergency wages. Cecily planned an audit, and you feared being branded a thief.',
      ['You diverted a repair allowance to wages.', 'You argued that the trust should benefit workers as well as family.'],
      'Protect the workers and keep your position.',
      [
        clueRound(['The proposed charitable trust would support injured workers.'], 'Explain why not every guest opposed the new will.'),
        clueRound(['The unexplained trust withdrawals were much larger than your repair allowance.'], 'Distinguish your own conduct from the missing fortune.'),
        clueRound(['Pell had told you there was no money available while approving transfers to his own practice.'], 'Corroborate the contradiction in the carbon account page.'),
      ], true),
    character('journalist', 'Julian Finch', 'The Society Reporter',
      'You were invited to cover a philanthropic announcement, not a household disaster.',
      'You hoped to publish a scandal about the trust. You promised discretion to gain an invitation and planned to break that promise.',
      ['You were preparing an expose.', 'You had secretly interviewed Felix about the family\'s finances.'],
      'Get a major story without losing your sources.',
      [
        clueRound(['Your invitation calls tonight an announcement of a charitable trust.'], 'Share its wording rather than repeat sensational rumors.'),
        clueRound(['A bank contact told you Cecily requested a review of trustee transactions.'], 'Reveal the inquiry while keeping the source unnamed.'),
        clueRound(['Your notes record Pell saying the old will was the only valid one before the announcement even began.'], 'Compare his insistence with the missing new will.'),
      ], true),
    character('cousin', 'Marian Vale', 'The Visiting Cousin',
      'You came to reconcile with Cecily after years of distance.',
      'You sold a family keepsake and let Felix take the blame. You meant to admit it tonight, but the household has found a worse subject.',
      ['You sold the keepsake.', 'You asked Cecily for financial help and were refused.'],
      'Repair your standing and avoid public embarrassment.',
      [
        clueRound(['Cecily planned to meet Pell privately before addressing the family.'], 'Share what she told you without inventing a sighting.'),
        clueRound(['She said the family could manage its inheritance without Pell.'], 'Support the finding that he, not the heirs, lost his position.'),
        clueRound(['You saw the duplicate will in Iris\'s tray before the alarm, so it was not written afterward.'], 'Corroborate the duplicate\'s existence and admit the keepsake secret.'),
      ], true),
  ],
};

export const STARTER_MYSTERIES = [
  {
    id: 'mercy-hollow',
    title: witchStory.title,
    blurb: 'Witch-trial panic, forged confessions and a stolen packet. Discover who turned a frightened village into a profitable lie.',
    inspiration: 'Salem-era suspicion and witch hearings; wholly fictional, with no supernatural knowledge required.',
    contentNote: 'Persecution, false accusations and an off-screen death. Witchcraft accusations are not evidence of guilt.',
    story: witchStory,
  },
  {
    id: 'blackthorn-farm',
    title: farmStory.title,
    blurb: 'Footsteps in the attic, a stranger in the snow and a land sale worth killing for. The outsider may be a story somebody planted.',
    inspiration: 'The isolated-farm atmosphere associated with Hinterkaifeck; not an answer to the real unsolved case.',
    contentNote: 'Isolation, staged haunting and an off-screen death. No child victims or graphic violence.',
    story: farmStory,
  },
  {
    id: 'briar-house',
    title: inheritanceStory.title,
    blurb: 'A missing will, a respectable household and a bell that cannot tell the whole truth. Follow the money before blaming the heirs.',
    inspiration: 'Victorian New England household tension associated with the Borden case; all characters and the solution are invented.',
    contentNote: 'Family conflict, financial fraud and an off-screen death. No graphic violence.',
    story: inheritanceStory,
  },
];
