import { chromium } from 'playwright';
import fs from 'fs';
const URL = process.argv[2];
const b = await chromium.launch(); const h = await b.newPage(); h.on('dialog', d => d.accept());
await h.goto(URL); await h.click('#btn-new');
await h.fill('#guests', 'Sarah\nMike\nPriya');
await h.click('[data-tab="paste"]');
await h.fill('#json', '{"title": "x", "characters": [{"name":"A"}], }');
await h.click('#load-json'); console.log('bad JSON ->', (await h.textContent('#errors')).trim().slice(0, 160));
await h.fill('#json', '{"title": "x", "rounds":[{"title":"r"}], "characters": [{"name":"A"},{"name":"B"}], "solution":{"killerId":"zz"}}');
await h.click('#load-json'); console.log('bad killer ->', (await h.textContent('#errors')).trim().slice(0, 200));
await h.fill('#json', fs.readFileSync('new URL('../examples/example-story.json', import.meta.url)', 'utf8'));
await h.click('#load-json'); await h.waitForSelector('#open-lobby'); console.log('example loaded ->', await h.inputValue('#f-title'));
await b.close();
